# docker-compose.yml
version: '3.8'
services:
  db:
    image: postgres:latest
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: yourpassword
  web:
    build: ./rest-api
    volumes:
      - ./rest-api:/app
    ports:
      - 8080:5000
    depends_on:
      - db

